package net.ytoec.kernel.client.edi;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "ISynOrderService", targetNamespace = "http://tempuri.org/")
public interface ISynOrderService {

	/**
	 * 
	 * @param lcId
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "GetOrders", action = "http://tempuri.org/ISynOrderService/GetOrders")
	@WebResult(name = "GetOrdersResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "GetOrders", targetNamespace = "http://tempuri.org/", className = "net.ytoec.kernel.client.edi.GetOrders")
	@ResponseWrapper(localName = "GetOrdersResponse", targetNamespace = "http://tempuri.org/", className = "net.ytoec.kernel.client.edi.GetOrdersResponse")
	public String getOrders(
			@WebParam(name = "lcId", targetNamespace = "http://tempuri.org/") String lcId);

	/**
	 * 
	 * @param lcId
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "GetOrdersV2", action = "http://tempuri.org/ISynOrderService/GetOrdersV2")
	@WebResult(name = "GetOrdersV2Result", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "GetOrdersV2", targetNamespace = "http://tempuri.org/", className = "net.ytoec.kernel.client.edi.GetOrdersV2")
	@ResponseWrapper(localName = "GetOrdersV2Response", targetNamespace = "http://tempuri.org/", className = "net.ytoec.kernel.client.edi.GetOrdersV2Response")
	public String getOrdersV2(
			@WebParam(name = "lcId", targetNamespace = "http://tempuri.org/") String lcId);

	/**
	 * 
	 * @param lcId
	 * @param waybills
	 * @return returns java.lang.Boolean
	 */
	@WebMethod(operationName = "SuccessOrders", action = "http://tempuri.org/ISynOrderService/SuccessOrders")
	@WebResult(name = "SuccessOrdersResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "SuccessOrders", targetNamespace = "http://tempuri.org/", className = "net.ytoec.kernel.client.edi.SuccessOrders")
	@ResponseWrapper(localName = "SuccessOrdersResponse", targetNamespace = "http://tempuri.org/", className = "net.ytoec.kernel.client.edi.SuccessOrdersResponse")
	public Boolean successOrders(
			@WebParam(name = "lcId", targetNamespace = "http://tempuri.org/") String lcId,
			@WebParam(name = "waybills", targetNamespace = "http://tempuri.org/") String waybills);

	/**
	 * 
	 * @param lcId
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "GetProvince", action = "http://tempuri.org/ISynOrderService/GetProvince")
	@WebResult(name = "GetProvinceResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "GetProvince", targetNamespace = "http://tempuri.org/", className = "net.ytoec.kernel.client.edi.GetProvince")
	@ResponseWrapper(localName = "GetProvinceResponse", targetNamespace = "http://tempuri.org/", className = "net.ytoec.kernel.client.edi.GetProvinceResponse")
	public String getProvince(
			@WebParam(name = "lcId", targetNamespace = "http://tempuri.org/") String lcId);

	/**
	 * 
	 * @param province
	 * @param lcId
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "GetCity", action = "http://tempuri.org/ISynOrderService/GetCity")
	@WebResult(name = "GetCityResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "GetCity", targetNamespace = "http://tempuri.org/", className = "net.ytoec.kernel.client.edi.GetCity")
	@ResponseWrapper(localName = "GetCityResponse", targetNamespace = "http://tempuri.org/", className = "net.ytoec.kernel.client.edi.GetCityResponse")
	public String getCity(
			@WebParam(name = "lcId", targetNamespace = "http://tempuri.org/") String lcId,
			@WebParam(name = "province", targetNamespace = "http://tempuri.org/") String province);

	/**
	 * 
	 * @param province
	 * @param lcId
	 * @param city
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "GetArea", action = "http://tempuri.org/ISynOrderService/GetArea")
	@WebResult(name = "GetAreaResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "GetArea", targetNamespace = "http://tempuri.org/", className = "net.ytoec.kernel.client.edi.GetArea")
	@ResponseWrapper(localName = "GetAreaResponse", targetNamespace = "http://tempuri.org/", className = "net.ytoec.kernel.client.edi.GetAreaResponse")
	public String getArea(
			@WebParam(name = "lcId", targetNamespace = "http://tempuri.org/") String lcId,
			@WebParam(name = "province", targetNamespace = "http://tempuri.org/") String province,
			@WebParam(name = "city", targetNamespace = "http://tempuri.org/") String city);

	/**
	 * 
	 * @param deliverInfo
	 * @param lcId
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "CommitDeliverInfo", action = "http://tempuri.org/ISynOrderService/CommitDeliverInfo")
	@WebResult(name = "CommitDeliverInfoResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "CommitDeliverInfo", targetNamespace = "http://tempuri.org/", className = "net.ytoec.kernel.client.edi.CommitDeliverInfo")
	@ResponseWrapper(localName = "CommitDeliverInfoResponse", targetNamespace = "http://tempuri.org/", className = "net.ytoec.kernel.client.edi.CommitDeliverInfoResponse")
	public String commitDeliverInfo(
			@WebParam(name = "lcId", targetNamespace = "http://tempuri.org/") String lcId,
			@WebParam(name = "deliverInfo", targetNamespace = "http://tempuri.org/") String deliverInfo);

	/**
	 * 
	 * @param lcId
	 * @param info
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "SynUserInfo", action = "http://tempuri.org/ISynOrderService/SynUserInfo")
	@WebResult(name = "SynUserInfoResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "SynUserInfo", targetNamespace = "http://tempuri.org/", className = "net.ytoec.kernel.client.edi.SynUserInfo")
	@ResponseWrapper(localName = "SynUserInfoResponse", targetNamespace = "http://tempuri.org/", className = "net.ytoec.kernel.client.edi.SynUserInfoResponse")
	public String synUserInfo(
			@WebParam(name = "lcId", targetNamespace = "http://tempuri.org/") String lcId,
			@WebParam(name = "info", targetNamespace = "http://tempuri.org/") String info);

	/**
	 * 
	 * @param lcid
	 * @param orders
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "CommitBackOrder", action = "http://tempuri.org/ISynOrderService/CommitBackOrder")
	@WebResult(name = "CommitBackOrderResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "CommitBackOrder", targetNamespace = "http://tempuri.org/", className = "net.ytoec.kernel.client.edi.CommitBackOrder")
	@ResponseWrapper(localName = "CommitBackOrderResponse", targetNamespace = "http://tempuri.org/", className = "net.ytoec.kernel.client.edi.CommitBackOrderResponse")
	public String commitBackOrder(
			@WebParam(name = "lcid", targetNamespace = "http://tempuri.org/") String lcid,
			@WebParam(name = "orders", targetNamespace = "http://tempuri.org/") String orders);

	/**
	 * 
	 * @param lcid
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "GetInBoundOrder", action = "http://tempuri.org/ISynOrderService/GetInBoundOrder")
	@WebResult(name = "GetInBoundOrderResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "GetInBoundOrder", targetNamespace = "http://tempuri.org/", className = "net.ytoec.kernel.client.edi.GetInBoundOrder")
	@ResponseWrapper(localName = "GetInBoundOrderResponse", targetNamespace = "http://tempuri.org/", className = "net.ytoec.kernel.client.edi.GetInBoundOrderResponse")
	public String getInBoundOrder(
			@WebParam(name = "lcid", targetNamespace = "http://tempuri.org/") String lcid);

	/**
	 * 
	 * @param lcid
	 * @param orders
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "CommitBackOrderStatus", action = "http://tempuri.org/ISynOrderService/CommitBackOrderStatus")
	@WebResult(name = "CommitBackOrderStatusResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "CommitBackOrderStatus", targetNamespace = "http://tempuri.org/", className = "net.ytoec.kernel.client.edi.CommitBackOrderStatus")
	@ResponseWrapper(localName = "CommitBackOrderStatusResponse", targetNamespace = "http://tempuri.org/", className = "net.ytoec.kernel.client.edi.CommitBackOrderStatusResponse")
	public String commitBackOrderStatus(
			@WebParam(name = "lcid", targetNamespace = "http://tempuri.org/") String lcid,
			@WebParam(name = "orders", targetNamespace = "http://tempuri.org/") String orders);

}
