package net.ytoec.kernel.client.edi;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * SynOrderService service = new SynOrderService();
 * ISynOrderService portType = service.getBasicHttpBindingISynOrderService();
 * portType.getOrders(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "SynOrderService", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://edi.wuliusys.com/SynOrderService.svc?wsdl")
public class SynOrderService extends Service {

	private final static URL SYNORDERSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(net.ytoec.kernel.client.edi.SynOrderService.class
					.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = net.ytoec.kernel.client.edi.SynOrderService.class
					.getResource(".");
			url = new URL(baseUrl,
					"http://edi.wuliusys.com/SynOrderService.svc?wsdl");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'http://edi.wuliusys.com/SynOrderService.svc?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		SYNORDERSERVICE_WSDL_LOCATION = url;
	}

	public SynOrderService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public SynOrderService() {
		super(SYNORDERSERVICE_WSDL_LOCATION, new QName("http://tempuri.org/",
				"SynOrderService"));
	}

	/**
	 * 
	 * @return returns ISynOrderService
	 */
	@WebEndpoint(name = "BasicHttpBinding_ISynOrderService")
	public ISynOrderService getBasicHttpBindingISynOrderService() {
		return super.getPort(new QName("http://tempuri.org/",
				"BasicHttpBinding_ISynOrderService"), ISynOrderService.class);
	}

}
