/**
 * 
 */
package net.ytoec.kernel.dataobject;

import java.util.Date;

/**
 * 问题件备注
 * @author wangyong
 * 2012-01-12
 */
public class QuestionaireRemark {

    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column
     * ec_core_questionaire_remark.id
     * 
     * @abatorgenerated Thu Jan 12 15:23:28 CST 2012
     */
    private Integer id;

    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column
     * ec_core_questionaire_remark.operator_name
     * 
     * @abatorgenerated Thu Jan 12 15:23:28 CST 2012
     */
    private String  operatorName;

    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column
     * ec_core_questionaire_remark.user_id
     * 
     * @abatorgenerated Thu Jan 12 15:23:28 CST 2012
     */
    private Integer  userId;

    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column
     * ec_core_questionaire_remark.questionaire_id
     * 
     * @abatorgenerated Thu Jan 12 15:23:28 CST 2012
     */
    private Integer questionaireId;

    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column
     * ec_core_questionaire_remark.create_time
     * 
     * @abatorgenerated Thu Jan 12 15:23:28 CST 2012
     */
    private Date    createTime;

    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column
     * ec_core_questionaire_remark.update_time
     * 
     * @abatorgenerated Thu Jan 12 15:23:28 CST 2012
     */
    private Date    updateTime;

    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column
     * ec_core_questionaire_remark.remak_content
     * 
     * @abatorgenerated Thu Jan 12 15:23:28 CST 2012
     */
    private String  remakContent;

    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column
     * ec_core_questionaire_remark.had_read
     * 
     * @abatorgenerated Thu Jan 12 15:23:28 CST 2012
     */
    private String  hadRead;//是否已读    0：未读     1：已读

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column
     * ec_core_questionaire_remark.id
     * 
     * @return the value of ec_core_questionaire_remark.id
     * @abatorgenerated Thu Jan 12 15:23:28 CST 2012
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column
     * ec_core_questionaire_remark.id
     * 
     * @param id the value for ec_core_questionaire_remark.id
     * @abatorgenerated Thu Jan 12 15:23:28 CST 2012
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column
     * ec_core_questionaire_remark.operator_name
     * 
     * @return the value of ec_core_questionaire_remark.operator_name
     * @abatorgenerated Thu Jan 12 15:23:28 CST 2012
     */
    public String getOperatorName() {
        return operatorName;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column
     * ec_core_questionaire_remark.operator_name
     * 
     * @param operatorName the value for ec_core_questionaire_remark.operator_name
     * @abatorgenerated Thu Jan 12 15:23:28 CST 2012
     */
    public void setOperatorName(String operatorName) {
        this.operatorName = operatorName;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column
     * ec_core_questionaire_remark.user_id
     * 
     * @return the value of ec_core_questionaire_remark.user_id
     * @abatorgenerated Thu Jan 12 15:23:28 CST 2012
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column
     * ec_core_questionaire_remark.user_id
     * 
     * @param userId the value for ec_core_questionaire_remark.user_id
     * @abatorgenerated Thu Jan 12 15:23:28 CST 2012
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column
     * ec_core_questionaire_remark.questionaire_id
     * 
     * @return the value of ec_core_questionaire_remark.questionaire_id
     * @abatorgenerated Thu Jan 12 15:23:28 CST 2012
     */
    public Integer getQuestionaireId() {
        return questionaireId;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column
     * ec_core_questionaire_remark.questionaire_id
     * 
     * @param questionaireId the value for ec_core_questionaire_remark.questionaire_id
     * @abatorgenerated Thu Jan 12 15:23:28 CST 2012
     */
    public void setQuestionaireId(Integer questionaireId) {
        this.questionaireId = questionaireId;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column
     * ec_core_questionaire_remark.create_time
     * 
     * @return the value of ec_core_questionaire_remark.create_time
     * @abatorgenerated Thu Jan 12 15:23:28 CST 2012
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column
     * ec_core_questionaire_remark.create_time
     * 
     * @param createTime the value for ec_core_questionaire_remark.create_time
     * @abatorgenerated Thu Jan 12 15:23:28 CST 2012
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column
     * ec_core_questionaire_remark.update_time
     * 
     * @return the value of ec_core_questionaire_remark.update_time
     * @abatorgenerated Thu Jan 12 15:23:28 CST 2012
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column
     * ec_core_questionaire_remark.update_time
     * 
     * @param updateTime the value for ec_core_questionaire_remark.update_time
     * @abatorgenerated Thu Jan 12 15:23:28 CST 2012
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column
     * ec_core_questionaire_remark.remak_content
     * 
     * @return the value of ec_core_questionaire_remark.remak_content
     * @abatorgenerated Thu Jan 12 15:23:28 CST 2012
     */
    public String getRemakContent() {
        return remakContent;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column
     * ec_core_questionaire_remark.remak_content
     * 
     * @param remakContent the value for ec_core_questionaire_remark.remak_content
     * @abatorgenerated Thu Jan 12 15:23:28 CST 2012
     */
    public void setRemakContent(String remakContent) {
        this.remakContent = remakContent;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column
     * ec_core_questionaire_remark.had_read
     * 
     * @return the value of ec_core_questionaire_remark.had_read
     * @abatorgenerated Thu Jan 12 15:23:28 CST 2012
     */
    public String getHadRead() {
        return hadRead;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column
     * ec_core_questionaire_remark.had_read
     * 
     * @param hadRead the value for ec_core_questionaire_remark.had_read
     * @abatorgenerated Thu Jan 12 15:23:28 CST 2012
     */
    public void setHadRead(String hadRead) {
        this.hadRead = hadRead;
    }
}
